/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanchen_anim_jni_BumimiDecode */

#ifndef _Included_com_fanchen_anim_jni_BumimiDecode
#define _Included_com_fanchen_anim_jni_BumimiDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanchen_anim_jni_BumimiDecode
 * Method:    decodeInfoJson
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_anim_jni_BumimiDecode_decodeInfoJson
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fanchen_anim_jni_BumimiDecode
 * Method:    decodeUrlJson
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_anim_jni_BumimiDecode_decodeUrlJson
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fanchen_anim_jni_BumimiDecode
 * Method:    signBiliParameter
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_anim_jni_BumimiDecode_signBiliParameter
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
